### ISSUE TITLE
Unsupported operating system android

### ISSUE THREAD

**Issue by susandahal** [zhzhzhy/Flutter-SDK-ARM64#10]
I'm trying to install it in termux but after replacing dart-sdk it downloads artifacts and says the above message.

Android Version: 13
Termux latest F droid version
![Screenshot_20230703-225350_Termux](https://github.com/zhzhzhy/Flutter-SDK-ARM64/assets/37948853/008736f3-7c86-464c-897f-d28fe21cb1cf)

**Comment by you814455** [comment]
Install linux and recompile using proot-distro
